"""
mocs.ecosystem — Open-Source Scientific Software Ecosystem Integrations.

Provides standardized providers, backend adapters, differential verification engines,
observable registry, and the authoritative OpenSourceEcosystemRegistry.

PASS 33: Maximum Open-Source Capability Harvest across 22 scientific domains (A-V),
expanded to 94 evaluated projects, 10 new canonical dataclasses, and 10 new backend
adapters and consensus engines with strict IP and copyleft firewalls.
"""

from .interfaces import (
    StructureSourceType,
    IntegrationStatus,
    QualityTier,
    LicenseClass,
    DomainScope,
    ObservableType,
    ProvenanceRecord,
    AtomRecord,
    CanonicalStructure,
    StructureProvider,
    AnalysisBackend,
    BackendDistanceResult,
    TrajectoryObservableResult,
    InteractionResult,
    CavityResult,
    CavitySetResult,
    AtomPair,
    DesignResult,
    PredictionResult,
    CrystallographicResult,
    WorkflowProvenanceNode,
    WorkflowProvenance,
    DiscrepancyClassification,
    DiscrepancyReport,
    CryoEMMapResult,
    SequenceDesignResult,
    ComplexPredictionResult,
    DockingPoseResult,
    DockingResultSet,
    PocketPredictionResult,
    PocketEnsembleResult,
    InteractionFingerprintResult,
    InteractionEnsembleResult,
    StructureSearchResult,
    SequenceHomologyResult,
    LigandValidationResult,
    EnsembleConsensusResult,
    DatasetBenchmarkSpec,
    SequenceStructureMapping,
)
from .providers import (
    RCSBStructureProvider,
    AlphaFoldDBProvider,
    SyntheticStructureProvider,
    GeneratedStructureProvider,
)
from .backends import (
    MDAnalysisBackend,
    NativeMOCSBackend,
    MDTrajBackendAdapter,
    RDKitBackendAdapter,
    OpenMMBackendAdapter,
    BiopythonBackendAdapter,
    BiotiteBackendAdapter,
    ProDyBackendAdapter,
    GemmiBackendAdapter,
    PLIPOracleAdapter,
    fpocketOracleAdapter,
    AutoDockVinaAdapter,
    pymbarAdapter,
    MRCMapAdapter,
    ProteinMPNNAdapter,
    BoltzAdapter,
    SminaDockingAdapter,
    P2RankAdapter,
    fpocketAdapter,
    ProLIFAdapter,
    FoldseekAdapter,
    MMseqs2Adapter,
    PoseBustersAdapter,
    SIFTSMappingAdapter,
    ConsensusPredictionEngine,
    PocketEnsembleEngine,
    BenchmarkLeakageDetector,
)
from .differential import DifferentialVerificationEngine
from .registry import (
    OpenSourceProject,
    ECOSYSTEM_PROJECTS,
    OpenSourceEcosystemRegistry,
)
from .observables import (
    ObservableDefinition,
    OBSERVABLE_REGISTRY,
    ObservableRegistry,
)
from .gap_analysis import (
    GapDecision,
    TAXONOMY_DOMAINS,
    CapabilityGap,
    CAPABILITY_GAPS,
    GapAnalysisRegistry,
)

__all__ = [
    # Interfaces
    "StructureSourceType",
    "IntegrationStatus",
    "QualityTier",
    "LicenseClass",
    "DomainScope",
    "ObservableType",
    "ProvenanceRecord",
    "AtomRecord",
    "CanonicalStructure",
    "StructureProvider",
    "AnalysisBackend",
    "BackendDistanceResult",
    "TrajectoryObservableResult",
    "InteractionResult",
    "CavityResult",
    "CavitySetResult",
    "AtomPair",
    "DesignResult",
    "PredictionResult",
    "CrystallographicResult",
    "WorkflowProvenanceNode",
    "WorkflowProvenance",
    "DiscrepancyClassification",
    "DiscrepancyReport",
    "CryoEMMapResult",
    "SequenceDesignResult",
    "ComplexPredictionResult",
    "DockingPoseResult",
    "DockingResultSet",
    "PocketPredictionResult",
    "PocketEnsembleResult",
    "InteractionFingerprintResult",
    "InteractionEnsembleResult",
    "StructureSearchResult",
    "SequenceHomologyResult",
    "LigandValidationResult",
    "EnsembleConsensusResult",
    "DatasetBenchmarkSpec",
    "SequenceStructureMapping",
    # Providers
    "RCSBStructureProvider",
    "AlphaFoldDBProvider",
    "SyntheticStructureProvider",
    "GeneratedStructureProvider",
    # Backends
    "MDAnalysisBackend",
    "NativeMOCSBackend",
    "MDTrajBackendAdapter",
    "RDKitBackendAdapter",
    "OpenMMBackendAdapter",
    "BiopythonBackendAdapter",
    "BiotiteBackendAdapter",
    "ProDyBackendAdapter",
    "GemmiBackendAdapter",
    "PLIPOracleAdapter",
    "fpocketOracleAdapter",
    "AutoDockVinaAdapter",
    "pymbarAdapter",
    "MRCMapAdapter",
    "ProteinMPNNAdapter",
    "BoltzAdapter",
    "SminaDockingAdapter",
    "P2RankAdapter",
    "fpocketAdapter",
    "ProLIFAdapter",
    "FoldseekAdapter",
    "MMseqs2Adapter",
    "PoseBustersAdapter",
    "SIFTSMappingAdapter",
    "ConsensusPredictionEngine",
    "PocketEnsembleEngine",
    "BenchmarkLeakageDetector",
    # Differential
    "DifferentialVerificationEngine",
    # Registry
    "OpenSourceProject",
    "ECOSYSTEM_PROJECTS",
    "OpenSourceEcosystemRegistry",
    # Observables
    "ObservableDefinition",
    "OBSERVABLE_REGISTRY",
    "ObservableRegistry",
    # Gap Analysis & Taxonomy (PASS 32/33)
    "GapDecision",
    "TAXONOMY_DOMAINS",
    "CapabilityGap",
    "CAPABILITY_GAPS",
    "GapAnalysisRegistry",
]
